### ISSUE TITLE
Some mandatory PTF settings were missing in the output.

### ISSUE THREAD

**Issue by Rawhound** [mehtadone/PT2PTF#1]
Hi, this is another great tool.  Just as feedback the below lines I needed to add manually as there is no corresponding PT settings (to my knowledge)

"MaxTrailingBuy" : "2",
"MinTrailingBuy" : "0.01",
"MaxTrailingProfit" : "2",
"MinTrailingProfit" : "0.01",

It was easy to work out these were missing as the PTF log told me.  Not sure if this is a defect or expected behavior so logged this issue anyway.

Thanks!

**Comment by mehtadone** [comment]
I made the assumption that people would want like for like so have "CalculateTrailingValues" as false in their appsettings.
